### PR TITLE
💄 Consulting template - Clean up UI

### LINKED ISSUE #69: 💄 Consulting template - Clean up UI
After building and adding multiple components to the consulting page, there is are some touch ups needed to make it look like the old site.

```[tasklist]
### Tasks
- [x] Fix section backgrounds
- [x] Add red seperators
- [ ] Check component order
- [ ] Resolve testimonials render error
```

Image
**Figure: White background needs to be full width (I think the parallax image need to have a fixed height)**

Image
**Figure: Need to add red seperator between sections**

image
**Figure: Render error occured on consulting page**

### PR DESCRIPTION
**Pull request by jimmidier**
Closes #69  #110 #111 #112 

- [x] Fix section backgrounds
- [x] Add red seperators
- [x] Check component order
- [x] Resolve testimonials render error
- [x] Add missing components

image
**Figure: Polished Testimonials block**

### CODE REVIEW

**Comment by wicksipedia** [comment]
Don't forget about the other components

image

**Comment by wicksipedia** [comment]
this needs to be rebased to pickup required changes from `main`

**Comment by wicksipedia** [comment]
I can see it has deployed ok now. It's just missing the last 2 components at the bottom of the template

image

**Comment by jimmidier** [comment]
> I can see it has deployed ok now. It's just missing the last 2 components at the bottom of the template
All done now

**Pull request merged**
